### ISSUE TITLE
MediaCodec$CodecException: Error 0x80001001

### ISSUE THREAD

**Issue by pfumagalli** [koush/vysor.io#102]
... From logcat:

```
D/AndroidRuntime( 2746): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
D/AndroidRuntime( 2746): CheckJNI is OFF
D/AndroidRuntime( 2746): Calling main entry com.koushikdutta.vysor.Main
I/VysorMain( 2746): Received command line password: 7c7bb2f
I/VysorMain( 2746): Server starting
I/VysorMain( 2746): Waiting for exit
I/VysorMain( 2746): Host: 127.0.0.1:53518
I/VysorMain( 2746): Connection: Upgrade
I/VysorMain( 2746): Pragma: no-cache
I/VysorMain( 2746): Cache-Control: no-cache
I/VysorMain( 2746): Upgrade: websocket
I/VysorMain( 2746): Origin: chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm
I/VysorMain( 2746): Sec-WebSocket-Version: 13
I/VysorMain( 2746): User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
I/VysorMain( 2746): Accept-Encoding: gzip, deflate, sdch
I/VysorMain( 2746): Accept-Language: en-US,en;q=0.8,it;q=0.6
I/VysorMain( 2746): Sec-WebSocket-Key: EXZ2AoE55aoIkwU4ZYibIg==
I/VysorMain( 2746): Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
I/VysorMain( 2746): Sec-WebSocket-Protocol: mirror-protocol
I/VysorMain( 2746): 
I/VysorMain( 2746): WebSocket authenticated: true
I/VysorMain( 2746): New raw socket accepted.
I/VysorMain( 2746): Got password 7c7bb2f
I/VysorMain( 2746): h264 authentication succeeded
I/VysorMain( 2746): registering virtual display
I/art     ( 2746): Thread[14,tid=2787,WaitingForJniOnLoad,Thread*=0xb899c4c0,peer=0x12d1fc10,"AsyncServer"] recursive attempt to load library "/system/lib/libmedia_jni.so"
D/MtpDeviceJNI( 2746): register_android_mtp_MtpDevice
I/art     ( 2746): Thread[14,tid=2787,WaitingForJniOnLoad,Thread*=0xb899c4c0,peer=0x12d1fc10,"AsyncServer"] recursive attempt to load library "/system/lib/libmedia_jni.so"
I/art     ( 2746): Thread[14,tid=2787,WaitingForJniOnLoad,Thread*=0xb899c4c0,peer=0x12d1fc10,"AsyncServer"] recursive attempt to load library "/system/lib/libmedia_jni.so"
W/AudioCapabilities( 2746): Unsupported mime audio/qcelp
W/AudioCapabilities( 2746): Unsupported mime audio/evrc
W/VideoCapabilities( 2746): Unsupported mime video/mp4v-esdp
I/VideoCapabilities( 2746): Unsupported profile 4 for video/mp4v-es
I/StdOutDevice( 2746): OMX.google.h264.encoder
I/StdOutDevice( 2746): colorFormat: 2135033992
I/StdOutDevice( 2746): colorFormat: 19
I/StdOutDevice( 2746): colorFormat: 21
I/StdOutDevice( 2746): colorFormat: 2130708361
I/StdOutDevice( 2746): profile/level: 1/32
I/StdOutDevice( 2746): Width: 416 Height: 240
I/StdOutDevice( 2746): Frame rate: 30
I/StdOutDevice( 2746): Creating encoder
I/OMXClient( 2746): Using client-side OMX mux.
E/OMXMaster( 2746): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
I/SoftAVCEncoder( 2746): Construct SoftAVCEncoder
I/StdOutDevice( 2746): Created encoder
I/StdOutDevice( 2746): Configuring encoder
W/ACodec  ( 2746): do not know color format 0x7f000789 = 2130708361
E/ACodec  ( 2746): OMX.google.h264.encoder does not support profile 1 @ level 800
I/ACodec  ( 2746): [OMX.google.h264.encoder] setupVideoEncoder failed
E/ACodec  ( 2746): [OMX.google.h264.encoder] configureCodec returning error -2147483648
E/ACodec  ( 2746): [OMX.google.h264.encoder] configureCodec returning error -2147483648
E/ACodec  ( 2746): signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec( 2746): Codec reported err 0x80001001, actionCode 0, while in state 3
E/MediaCodec( 2746): configure failed with err 0x80001001, resetting...
I/OMXClient( 2746): Using client-side OMX mux.
E/OMXMaster( 2746): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
I/SoftAVCEncoder( 2746): Construct SoftAVCEncoder
E/NIO     ( 2746): Unhandled exception
E/NIO     ( 2746): android.media.MediaCodec$CodecException: Error 0x80001001
E/NIO     ( 2746): 	at android.media.MediaCodec.native_configure(Native Method)
E/NIO     ( 2746): 	at android.media.MediaCodec.configure(MediaCodec.java:577)
E/NIO     ( 2746): 	at com.koushikdutta.virtualdisplay.EncoderDevice.createDisplaySurface(EncoderDevice.java:434)
E/NIO     ( 2746): 	at com.koushikdutta.virtualdisplay.EncoderDevice.registerVirtualDisplay(EncoderDevice.java:48)
E/NIO     ( 2746): 	at com.koushikdutta.vysor.Main.writer(Main.java:126)
E/NIO     ( 2746): 	at com.koushikdutta.vysor.Main$8.onAuthenticated(Main.java:467)
E/NIO     ( 2746): 	at com.koushikdutta.vysor.Main$8$2.onStringAvailable(Main.java:495)
E/NIO     ( 2746): 	at com.koushikdutta.async.LineEmitter.onDataAvailable(LineEmitter.java:27)
E/NIO     ( 2746): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
E/NIO     ( 2746): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
E/NIO     ( 2746): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
E/NIO     ( 2746): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
E/NIO     ( 2746): 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
E/NIO     ( 2746): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
I/VysorMain( 2746): Connection terminated.
```

**Comment by pfumagalli** [comment]
Obvious other symptoms, Mac side saying that Android can not be reached, and Android saying all is good :-)

**Comment by koush** [comment]
your device does not have a hardware encoder.

**Comment by linroid** [comment]
Nothing to preview.
Nothing to preview.
Nothing to preview.
Nothing to preview.
Nothing to preview.
