### ISSUE TITLE
Android 14 Beta 3: Vysor failing to connect with Connection Error

### ISSUE THREAD

**Issue by shenoy008** [koush/vysor.io#1278]
Hello, I have a Pixel 5 device that is running Android 14 Beta 3, and I recently discovered that I am unable to view my phone through my Mac laptop. I've already turned on USB debugging and restarted my phone and laptop. I keep getting Connection Error

OS: MacOS Mojave 10.14.6
Device: Pixel 5
Android 14 Beta 3
Vysor Version 5.0.16
Vysor Bug Report Link: https://gist.github.com/VysorLogs/ff893f329572025f1e605b8102660639

**Comment by shenoy008** [comment]
@koush Please suggest

**Comment by cidfarzan** [comment]
same problem, updated to android 13 beta 3 last night, both pc windows 10 and 11 computers would not connect, identifies device, tries to connect, then error, rebooted phone, disabled usb debugging, uninstalled and reinstalled vysor, need help.

OS: windows 10 / Windows 11
Device : Pixel 7 Pro
Android 14 Beta 3
Vysor Version 5.0.16 runtime 5.0.7
Vysor Bug Remport Link  [https://gist.github.com/VysorLogs/75b8ca826fc8c5793fce13172f0a9bb8]
((https://gist.github.com/VysorLogs/75b8ca826fc8c5793fce13172f0a9bb8))

**Comment by cidfarzan** [comment]
@koush Please suggest

**Comment by shenoy008** [comment]
Hi @koush 
Did you get a chance to look into the new issue ? Any suggestions or workaround ?

**Comment by cidfarzan** [comment]
please help

**Comment by cidfarzan** [comment]
thank you for fixing it @koush  you are amazing
@shenoy008 switch to beta channel on the desktop app, there is a fix now , all working

**Comment by shenoy008** [comment]
Awesome. Thanks a lot @koush , @cidfarzan . Kudos

**Comment by vilasrk** [comment]
@koush 
Can you please share procedure to switch to beta channel?
And also is there any procedure to compile vysor with your PR.

Please help to share details

**Comment by gerardoeg** [comment]
Confirmed the fix 5.0.36, which you can found in the beta channel in:

Vysor main screen / Advanced / Switch to beta channel

CC @vilasrk

**Comment by gerardoeg** [comment]
![image](https://github.com/koush/vysor.io/assets/113394661/3bd4360e-7672-4cdc-ad23-fc542eb01028)

**Comment by vilasrk** [comment]
It is not working

**Comment by vilasrk** [comment]
08-09 08:47:50.292  2807  2807 I Vysor   : Server starting
08-09 08:47:50.292  2807  2807 E VysorControl: Clipboard setup failed
08-09 08:47:50.292  2807  2807 E VysorControl: java.lang.RuntimeException: Not implemented. Must override in a subclass.
08-09 08:47:50.292  2807  2807 E VysorControl:  at android.content.Context.getDeviceId(Context.java:7608)
08-09 08:47:50.292  2807  2807 E VysorControl:  at android.content.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:308)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.koushikdutta.vysor.Clipboard$Companion$clipboard$1.addPrimaryClipChangedListener(Unknown Source:12)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.koushikdutta.vysor.VysorDaemonBase.setupClipboard(Unknown Source:14)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.koushikdutta.vysor.VysorDaemonBase.start(Unknown Source:0)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.koushikdutta.vysor.VysorDaemon.start(Unknown Source:0)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.koushikdutta.vysor.Main.main(Unknown Source:114)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.koushikdutta.vysor.ProtocolCheckMain.main(Unknown Source:76)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-09 08:47:50.292  2807  2807 E VysorControl:  at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by vilasrk** [comment]
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:103)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1280

**Comment by vilasrk** [comment]
With scrcpy still seeing this error
