### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by AsSeenonTV** [koush/vysor.io#230]
Hello,

The issue I'm finding is that while on Mac OS X with Vysor (Desktop Version), I am able to connect with my device, and all inputs seem to be working (Swipe, tap, etc.), even when I use the screenshot option, it works.  However, when I actually load the application and it says it's connected, all I see is a black screen.  I have seen issues that seem related, such as https://github.com/koush/vysor.io/issues/186, but they seem related to Windows machines and/or the chrome app.

My details:

OS: Mac OS X 10.11.6
Vysor: Desktop version, Version 1.6.7
Device: ONE A2005 (One Plus 2, Android device

If any other details are needed, please let me know.,

**Comment by koush** [comment]
a logcat would be helpful

**Comment by neyron91** [comment]
```
03-14 05:05:51.057 4512-4522/? I/StdOutDevice: Creating input surface
03-14 05:05:51.057 593-593/? E/OMXNodeInstance: getParameter(4f:IMG.TOPAZ.Encoder, ParamConsumerUsageBits(0x6f800004)) ERROR: UnsupportedIndex(0x8000101a)
03-14 05:05:51.058 4512-4522/? I/StdOutDevice: Starting Encoder
03-14 05:05:51.074 4944-4944/? I/VysorMain: Received command line password: 2caf4d19
03-14 05:05:51.079 4512-4522/? I/StdOutDevice: Surface ready
03-14 05:05:51.080 4512-4522/? I/StdOutDevice: Encoder ready
03-14 05:05:51.080 4512-4522/? E/StdOutDevice: Created surface
03-14 05:05:51.080 4512-4987/? I/StdOutDevice: Writer started.
03-14 05:05:51.080 4512-4987/? I/StdOutDevice: MediaCodec.INFO_OUTPUT_FORMAT_CHANGED
03-14 05:05:51.080 4512-4987/? I/StdOutDevice: output width: 528
03-14 05:05:51.080 4512-4987/? I/StdOutDevice: output height: 960
03-14 05:05:51.080 4512-4987/? I/StdOutDevice: Got first buffer
03-14 05:05:51.089 4944-4944/? I/VysorMain: Found IME hooks.
03-14 05:05:51.090 4944-4944/? I/VysorMain: Server starting
03-14 05:05:51.093 317-317/? I/gralloc: Alloc req: dev=0x7f85002460, w=528, h=960, format=0x1, usage=0x410800
03-14 05:05:51.094 4512-4522/? I/VysorMain: virtual display registered
03-14 05:05:51.095 317-317/? I/gralloc: Alloc handle(0x7f79f44400): interfmt=0x1, stride=576, size=2211840, usage=0x410800
03-14 05:05:51.095 4512-4558/? I/StdOutDevice: Writer done
03-14 05:05:51.096 317-1824/? I/gralloc: Free handle(0x7f79f44400)
03-14 05:05:51.096 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3747: 
03-14 05:05:51.096 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3749: 
03-14 05:05:51.096 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3763: 
03-14 05:05:51.096 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3765: 
03-14 05:05:51.096 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3780: 
03-14 05:05:51.096 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3782: 
03-14 05:05:51.097 593-1531/? W/GraphicBufferSource: Dropped back down to Loaded without Executing
03-14 05:05:51.098 317-317/? I/gralloc: Alloc req: dev=0x7f85002460, w=528, h=960, format=0x1, usage=0x410a00
03-14 05:05:51.098 593-1531/? W/GraphicBufferSource: potential buffer leak (acquired -370)
03-14 05:05:51.099 317-317/? I/gralloc: Alloc handle(0x7f7fd18400): interfmt=0x1, stride=576, size=2211840, usage=0x410a00
03-14 05:05:51.100 317-349/? I/gralloc: Free handle(0x7f7fd18400)
03-14 05:05:51.100 4512-4522/? I/VysorMain: Connection terminated.
03-14 05:05:51.101 4512-4522/? I/VysorFactory: VirtualDisplay released
03-14 05:05:51.101 593-4983/? E/IMGTOPAZ: IMG_ENC send EOS to psQueuePairQ in OTE_Video_EmptyBufferTask at line:5732
03-14 05:05:51.101 4512-4522/? I/VysorFactory: factory released
03-14 05:05:51.101 593-4985/? E/IMGTOPAZ: IMG_ENC receive EOS from psQueuePairQ in OTE_Video_EncodeStreamTask at line:5342
03-14 05:05:51.101 593-4985/? E/IMGTOPAZ: IMG_ENC push EOS in sOutBufUsed in OTE_Video_EncodeStreamTask at line:5378
03-14 05:05:51.101 593-4985/? E/IMGTOPAZ: IMG_ENC Before EmptyBufferDone in EncodeStreamTask at line:5383
03-14 05:05:51.101 593-4984/? E/IMGTOPAZ: IMG_ENC FBT : EmptyBuffer command recieved bEOS_Coded:0 OTE_QUEUE_IsNotEmpty(&psCtxVideo->sInpBufUnused):0 in OTE_Video_FillBufferTask at line:6339
03-14 05:05:51.101 593-4985/? E/IMGTOPAZ: IMG_ENC After EmptyBufferDone in EncodeStreamTask at line:5385
03-14 05:05:51.101 593-4984/? E/IMGTOPAZ: IMG_ENC before OTE_QUEUE_PopWait in FillBufferTask at line:6348
03-14 05:05:51.101 593-4984/? E/IMGTOPAZ: IMG_ENC before IMG_V_AbortStream in FillBufferTask at line:6350
03-14 05:05:51.101 593-4984/? E/IMGTOPAZ: IMG_ENC before IMG_C_WaitOnSync in FillBufferTask at line:6353
03-14 05:05:51.101 593-4984/? E/IMGTOPAZ: IMG_ENC After IMG_C_WaitOnSync in FillBufferTask at line:6355
03-14 05:05:51.101 593-4984/? E/IMGTOPAZ: IMG_ENC before FillBufferDone in FillBufferTask at line:6370
03-14 05:05:51.101 593-4984/? E/IMGTOPAZ: IMG_ENC After FillBufferDone in FillBufferTask at line:6372
03-14 05:05:51.104 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3863: 
03-14 05:05:51.104 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3865: 
03-14 05:05:51.104 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3875: 
03-14 05:05:51.104 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3877: 
03-14 05:05:51.104 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3889: 
03-14 05:05:51.104 593-4552/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3891: 
03-14 05:05:51.105 4944-4988/? E/NIO: wtf
                                      java.net.BindException: bind failed: EADDRINUSE (Address already in use)
                                          at libcore.io.IoBridge.bind(IoBridge.java:99)
                                          at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
                                          at java.net.ServerSocket.bind(ServerSocket.java:348)
                                          at java.net.ServerSocket.bind(ServerSocket.java:308)
                                          at com.koushikdutta.async.AsyncServer$5.run(SourceFile:315)
                                          at com.koushikdutta.async.AsyncServer$3.run(SourceFile:210)
                                          at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:739)
                                          at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:757)
                                          at com.koushikdutta.async.AsyncServer.run(SourceFile:657)
                                          at com.koushikdutta.async.AsyncServer.access$800(SourceFile:44)
                                          at com.koushikdutta.async.AsyncServer$14.run(SourceFile:599)
                                       Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
                                          at libcore.io.Posix.bind(Native Method)
                                          at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
                                          at libcore.io.IoBridge.bind(IoBridge.java:97)
                                          at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132) 
                                          at java.net.ServerSocket.bind(ServerSocket.java:348) 
                                          at java.net.ServerSocket.bind(ServerSocket.java:308) 
                                          at com.koushikdutta.async.AsyncServer$5.run(SourceFile:315) 
                                          at com.koushikdutta.async.AsyncServer$3.run(SourceFile:210) 
                                          at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:739) 
                                          at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:757) 
                                          at com.koushikdutta.async.AsyncServer.run(SourceFile:657) 
                                          at com.koushikdutta.async.AsyncServer.access$800(SourceFile:44) 
                                          at com.koushikdutta.async.AsyncServer$14.run(SourceFile:599) 
03-14 05:05:51.106 4512-4987/? I/StdOutDevice: Writer done
03-14 05:05:51.107 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3747: 
03-14 05:05:51.107 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3749: 
03-14 05:05:51.107 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3763: 
03-14 05:05:51.107 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3765: 
03-14 05:05:51.107 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3780: 
03-14 05:05:51.107 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3782: 
03-14 05:05:51.107 593-866/? W/GraphicBufferSource: Dropped back down to Loaded without Executing
03-14 05:05:51.108 4512-4522/? I/VysorMain: Connection terminated.
03-14 05:05:51.110 4944-4991/? E/NIO: wtf
                                      java.net.BindException: bind failed: EADDRINUSE (Address already in use)
                                          at libcore.io.IoBridge.bind(IoBridge.java:99)
                                          at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
                                          at java.net.ServerSocket.bind(ServerSocket.java:348)
                                          at java.net.ServerSocket.bind(ServerSocket.java:308)
                                          at com.koushikdutta.async.AsyncServer$5.run(SourceFile:315)
                                          at com.koushikdutta.async.AsyncServer$3.run(SourceFile:210)
                                          at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:739)
                                          at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:757)
                                          at com.koushikdutta.async.AsyncServer.run(SourceFile:657)
                                          at com.koushikdutta.async.AsyncServer.access$800(SourceFile:44)
                                          at com.koushikdutta.async.AsyncServer$14.run(SourceFile:599)
                                       Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
                                          at libcore.io.Posix.bind(Native Method)
                                          at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
                                          at libcore.io.IoBridge.bind(IoBridge.java:97)
                                          at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132) 
                                          at java.net.ServerSocket.bind(ServerSocket.java:348) 
                                          at java.net.ServerSocket.bind(ServerSocket.java:308) 
                                          at com.koushikdutta.async.AsyncServer$5.run(SourceFile:315) 
                                          at com.koushikdutta.async.AsyncServer$3.run(SourceFile:210) 
                                          at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:739) 
                                          at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:757) 
                                          at com.koushikdutta.async.AsyncServer.run(SourceFile:657) 
                                          at com.koushikdutta.async.AsyncServer.access$800(SourceFile:44) 
                                          at com.koushikdutta.async.AsyncServer$14.run(SourceFile:599) 
03-14 05:05:51.111 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3863: 
03-14 05:05:51.111 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3865: 
03-14 05:05:51.111 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3875: 
03-14 05:05:51.112 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3877: 
03-14 05:05:51.112 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3889: 
03-14 05:05:51.112 593-4978/? I/img_ote_base: Function OTE_Base_SendCtrlBuffer: call OSA_ThreadSyncWait at line 3891: 
03-14 05:05:51.112 4944-4992/? E/NIO: wtf
                                      java.net.BindException: bind failed: EADDRINUSE (Address already in use)
                                          at libcore.io.IoBridge.bind(IoBridge.java:99)
                                          at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
                                          at java.net.ServerSocket.bind(ServerSocket.java:348)
                                          at java.net.ServerSocket.bind(ServerSocket.java:308)
                                          at com.koushikdutta.async.AsyncServer$5.run(SourceFile:315)
                                          at com.koushikdutta.async.AsyncServer$3.run(SourceFile:210)
                                          at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:739)
                                          at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:757)
                                          at com.koushikdutta.async.AsyncServer.run(SourceFile:657)
                                          at com.koushikdutta.async.AsyncServer.access$800(SourceFile:44)
                                          at com.koushikdutta.async.AsyncServer$14.run(SourceFile:599)
                                       Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
                                          at libcore.io.Posix.bind(Native Method)
                                          at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
                                          at libcore.io.IoBridge.bind(IoBridge.java:97)
                                          at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132) 
                                          at java.net.ServerSocket.bind(ServerSocket.java:348) 
                                          at java.net.ServerSocket.bind(ServerSocket.java:308) 
                                          at com.koushikdutta.async.AsyncServer$5.run(SourceFile:315) 
                                          at com.koushikdutta.async.AsyncServer$3.run(SourceFile:210) 
                                          at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:739) 
                                          at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:757) 
                                          at com.koushikdutta.async.AsyncServer.run(SourceFile:657) 
                                          at com.koushikdutta.async.AsyncServer.access$800(SourceFile:44) 
                                          at com.koushikdutta.async.AsyncServer$14.run(SourceFile:599) 
03-14 05:05:51.112 4944-4944/? E/VysorMain: No server socket?
03-14 05:05:51.113 4944-4944/? I/Process: Sending signal. PID: 4944 SIG: 9
03-14 05:05:51.116 2048-2069/? I/PgedBinderListener: kstate callback type:8 value1=4944 value2=KILLED
03-14 05:05:51.117 593-1266/? E/BufferQueueProducer: [GraphicBufferSource] queueBuffer: BufferQueue has been abandoned
03-14 05:05:51.125 4512-4558/? I/StdOutDevice: =======ENCODING COMPELTE=======
03-14 05:05:51.138 957-1471/? W/System.err: java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_DEVICE_STATS.
03-14 05:05:51.138 957-1471/? W/System.err:     at android.app.ContextImpl.enforce(ContextImpl.java:1599)
03-14 05:05:51.138 957-1471/? W/System.err:     at android.app.ContextImpl.enforcePermission(ContextImpl.java:1612)
03-14 05:05:51.138 957-1471/? W/System.err:     at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1038)
03-14 05:05:51.138 957-1471/? W/System.err:     at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:711)
03-14 05:05:51.138 957-1471/? W/System.err:     at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
03-14 05:05:51.138 957-1471/? W/System.err:     at android.os.Binder.execTransact(Binder.java:453)
03-14 05:05:51.139 4512-4987/? I/StdOutDevice: =======ENCODING COMPELTE=======
```
