### ISSUE TITLE
Vysor crashes when connecting device to computer - "not allowed to start service intent"

### ISSUE THREAD

**Issue by kyleparker** [koush/vysor.io#262]
Pixel XL running O preview (version 8.0.0, May 5 2017 security patch level)
Windows 10 based machine

Every time I plug my device in, I get a "Vysor has stopped" dialog with "Close app". I'm still able to see my device on the computer, but the message appears each time the device is plugged in.

Here's the stacktrace:

```
07-14 22:01:01.004 3139-3139/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.koushikdutta.vysor, PID: 3139
java.lang.RuntimeException: Unable to start receiver com.koushikdutta.vysor.CharCodeReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { flg=0x10 cmp=com.koushikdutta.vysor/.VysorIME (has extras) }: app is in background uid UidRecord{dca34e4 u0a139 RCVR idle procs:1 seq(0,0,0)}
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
at android.app.ActivityThread.-wrap17(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { flg=0x10 cmp=com.koushikdutta.vysor/.VysorIME (has extras) }: app is in background uid UidRecord{dca34e4 u0a139 RCVR idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1499)
at android.app.ContextImpl.startService(ContextImpl.java:1455)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at com.koushikdutta.vysor.CharCodeReceiver.onReceive(CharCodeReceiver.java:17)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
at android.app.ActivityThread.-wrap17(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6541) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by koush** [comment]
Just tested on the same device/version and no issue here. I'll leave this open until after O releases properly. May wanna give the device a restart.

**Comment by koush** [comment]
Could also try uninstalling Vysor. Some component may be in a bad state.

**Comment by kyleparker** [comment]
I'll give the uninstall a try - encountering the same behaviour on three
separate machines, but all the same phone. I'll report back after
uninstalling and reconnecting. Thanks for the help.

**Comment by kyleparker** [comment]
Uninstalling the app and restarting the device did not work - still encountering the issue when plugging the Pixel into any Window 10 machine. I'm running v1.7.3.

It's not a big deal, doesn't seem to cause any harm. Just wanted to pass it along.

Still an amazing tool that I use every single day. Thank you!

**Comment by koush** [comment]
Are you rooted or something?

**Comment by kyleparker** [comment]
No, stock Pixel with no mods or any custom settings.

**Comment by koush** [comment]
Hm, I have an OTA for my Pixel on O, let me check again.

**Comment by koush** [comment]
Still working fine on the latest OTA.

**Comment by koush** [comment]
Ok, just got the error. Can't reproduce it now. I think the best I can do is just mask the exception. Not exactly sure why it is happening.

**Comment by koush** [comment]
Seems to be related to first install.

**Comment by kyleparker** [comment]
Glad I'm not completely crazy :-) I've not noticed it actually causing a
problem, so masking it shouldn't be an issue. Everything seems to be work
as expected once I dismiss the dialog.

**Comment by ericksprengel** [comment]
I think it happens because of Android O Service limitations.
You can't start a Service from a Receiver. The Vysor probably is receiving an Intent for "usb plugged" and it trying to start a Service (com.koushikdutta.vysor/.VysorIME). This Service must be replaced by JobScheduler implementation for Android O.

In few words the Service is started right now while the JobScheduler will start it according to JobInfo.

**Comment by koush** [comment]
@ericksprengel Yeah, that's roughly what I'm doing. The IME is started by the receiver. I'll take a look at JobScheduler. I thought I had fixed this (catching the exception to at least hide it). I wonder if I never released the apk?
