### ISSUE TITLE
Linux - stuck on wheel

### ISSUE THREAD

**Issue by pegordo** [koush/vysor.io#37]
Vysor keeps showing "the wheel" after pressing Ok on the device.

Chrome - Version 44.0.2403.157 (64-bit)
Android - 4.4.2
Vysor: 1.0.4.8

Update

After a few seconds I have this on console:
Broadway Configured: {"filter":"original","filterHorLuma":"optimized","filterVerLumaEdge":"optimized","getBoundaryStrengthsA":"optimized"}
Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
WebSocket connection to 'ws://127.0.0.1:53519/input' failed: Connection closed before receiving a handshake response

![screenshot-vysor beta](https://cloud.githubusercontent.com/assets/14006980/9547133/047404be-4d90-11e5-8260-5af9cd35859c.png)
![screenshot-developer tools - chrome-extension --gidgenkbbabolejbgbpnhbimgjbffefm-screen html](https://cloud.githubusercontent.com/assets/14006980/9547134/047634c8-4d90-11e5-9e30-7da648ead58f.png)

**Comment by koush** [comment]
Can you get me the log from teh background page too?

**Comment by pegordo** [comment]
![background-screenshot - 01-09-2015 - 02 24 57](https://cloud.githubusercontent.com/assets/14006980/9594290/2de79ef0-5051-11e5-859f-4d571bd4dea0.png)

**Comment by pegordo** [comment]
Error in event handler for sockets.tcp.onReceive: TypeError: Cannot read property 'contentWindow' of undefined
    at chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:2:27874
    at chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:2:11181
    at chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:2:9978
    at Socket.read (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:7961)
    at chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:2:9954
    at Socket.read (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:7961)
    at chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:2:9815
    at Socket.read (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:7961)
    at Socket.dataReceived (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:8947)
    at chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:5529
serial 8DNBFAZSJ7QOC6PV
protocol version: vysor-io-5
got main socket Socket
set password

**Comment by koush** [comment]
this might be fixed in 1052.

**Comment by pegordo** [comment]
Thanks

**Comment by gnobal** [comment]
I get the same "stuck on wheel" thing on a Nexus 4 (Android 5.1) connected to Ubuntu 15.04 (updated):

Background page log:
````
Vysor version 1.0.5.7
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.22 Safari/537.36
gcm registration APA91bF6DzGErmW_BevAPIg-U1Bsuzmtzw8OwjLTlIaEMF7S4iet8pAJRISPOWh21vJoad9Xg6a04V0bZquORYmut9CoPwwjKOBcLhlpkb-TOgLAMPElXaXf2zCah7HP5lHRDNbkvtL7-_1uFylWhQTBem30UeSyyA
got interfaces [{"alternateSetting":0,"endpoints":[{"address":129,"direction":"in","extra_data":{},"maximumPacketSize":512,"pollingInterval":0,"type":"bulk","usage":"data"},{"address":1,"direction":"out","extra_data":{},"maximumPacketSize":512,"pollingInterval":0,"type":"bulk","usage":"data"},{"address":130,"direction":"in","extra_data":{},"maximumPacketSize":28,"pollingInterval":6,"type":"interrupt","usage":"data"}],"extra_data":{},"interfaceClass":255,"interfaceNumber":0,"interfaceProtocol":0,"interfaceSubclass":255},{"alternateSetting":0,"endpoints":[{"address":131,"direction":"in","extra_data":{},"maximumPacketSize":512,"pollingInterval":0,"type":"bulk","usage":"data"},{"address":2,"direction":"out","extra_data":{},"maximumPacketSize":512,"pollingInterval":0,"type":"bulk","usage":"data"}],"extra_data":{},"interfaceClass":255,"interfaceNumber":1,"interfaceProtocol":1,"interfaceSubclass":66}]
claiming: {"handle":12,"productId":20194,"vendorId":6353} {"alternateSetting":0,"endpoints":[{"address":131,"direction":"in","extra_data":{},"maximumPacketSize":512,"pollingInterval":0,"type":"bulk","usage":"data"},{"address":2,"direction":"out","extra_data":{},"maximumPacketSize":512,"pollingInterval":0,"type":"bulk","usage":"data"}],"extra_data":{},"interfaceClass":255,"interfaceNumber":1,"interfaceProtocol":1,"interfaceSubclass":66}
claimed: undefined
connecting
sending CNXN
starting receive loop
ADB Server started
auth: AdbDevice
found device: 018a5828202feefd
installing apk
fatal error {"data":{},"resultCode":1}
Unchecked runtime.lastError while running usb.bulkTransfer: Transfer failed.
    at AdbUsbTransport.read (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:21727)
    at AdbDevice.receiveMessages (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:26953)
    at AdbDevice.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:29264)
fatal error {"data":{},"resultCode":1}
Unchecked runtime.lastError while running usb.bulkTransfer: Transfer failed.
    at AdbUsbTransport.write (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:21345)
    at AdbUsbTransport.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:21557)
Unchecked runtime.lastError while running usb.releaseInterface: Error releasing interface.
    at AdbUsbTransport.destroy (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:20939)
    at AdbDevice.destroy (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:23164)
    at AdbDevice.fatal (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:22929)
    at AdbDevice.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:24817)
    at AdbUsbTransport.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:21415)
Unchecked runtime.lastError while running sockets.tcpServer.close: Socket not found
    at Server.destroy (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:9662)
    at Server.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:23137)
    at Function.n.extend.each (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/common/jquery-2.1.1.min.js:2:2934)
    at AdbDevice.destroy (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:23085)
    at AdbDevice.fatal (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:22929)
    at AdbDevice.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:24817)
    at AdbUsbTransport.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:21415)
Unchecked runtime.lastError while running usb.closeDevice: No such connection.
    at AdbUsbTransport.<anonymous> (chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/uglify.js:1:21017)
````

screen.html log:
````
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
increasing TOTAL_MEMORY to 67108864 to be compliant with the asm.js spec (and given that TOTAL_STACK=5242880)
pre-main prep time: 1 ms
````

**Comment by koush** [comment]
@gnobal https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp
