### ISSUE TITLE
Reproducible IllegalStateException on typing non-ASCII characters with setting 'International Keyboard'

### ISSUE THREAD

**Issue by TitusLabienus** [koush/vysor.io#557]
**Describe the bug**
Vysor throws since the 3.x.x versions (tested on 3.0.84) an IllegalStateException on the Android device side reproducibly. With the latest 2.x.x version it works normally. Possibly related to #555. However, in contrast to #555 the international keyboard does not work 100% of the times for me trying to type international characters with 3.x.x, and the app crashes too.
 

**Attach a Vysor Bug Report Log**
I have already downgraded to 2.x.x version, as 3.x.x is unusable for me for that reason. If really needed (It is also reproducible 100% of the times), I can reinstall it though. However, I have the exception message:

`java.lang.IllegalStateException: IInputMethodPrivilegedOperations must be set at most once. privOps=com.android.internal.inputmethod.IInputMethodPrivilegedOperations$Stub$Proxy@b0a3a70
	at com.android.internal.inputmethod.InputMethodPrivilegedOperations$OpsHolder.set(InputMethodPrivilegedOperations.java:52)
	at com.android.internal.inputmethod.InputMethodPrivilegedOperations.set(InputMethodPrivilegedOperations.java:94)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.initializeInternal(InputMethodService.java:692)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:180)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)`

**To Reproduce**
1. (optional; Vysor crashes without too) Run some exception catcher on the Android device to detect exceptions (e.g. Scoop)
2. Enalbe 'International Keyboard'
2. Click 'View'
3. Type some non-ASCII character (e.g. Chinese or Thai letters) 
4. Note that typing does not work and that the Vysor app on the device crashes with mentioned IllegalStateException

**Expected behavior**
Vysor does not crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Vysor Version 3.0.84

**Android (please complete the following information):**
 - Device: Note9
 - OS: Android 10
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
Awesome. Thanks so much for the logcat.
I've seen this issue, and I'm unsure why it is happening. The stack shows that the error is entirely within the framework.

I'll need to poke at it to find out what's causing it to crash.

**Comment by koush** [comment]
I'm not seeing this anymore, and think it was fixed in later versions of android. There's no Vysor fix because the issue seems to be entirely in the framework with no workaround.

**Comment by TitusLabienus** [comment]
@koush Yes, I have retried it now, and the issue seems to be resolved
