### ISSUE TITLE
Encoder Error Exception

### ISSUE THREAD

**Issue by shervinafshar** [koush/vysor.io#670]
Hello. I'm not sure if this is a bug or it's my setup, but I thought to ask here. I'm trying to use Vysor on a Lenovo VR-1541F (which is a standalone Android Daydream VR headset). The instructions were followed and all the steps has taken. A license has been purchased to make sure if it might be happening with USB-only or Wifi-only or both (it happens with both). Here are the exception logs from the devices when trying to connect through USB or Wifi (lines redacted for brevity):

```12-13 14:00:06.878  6684  6698 E StdOutDevice: Error getting media profiles
12-13 14:00:06.878  6684  6698 E StdOutDevice: java.io.FileNotFoundException: /system/etc/media_profiles.xml (No such file or directory)
12-13 14:00:06.878  6684  6698 E StdOutDevice: 	at java.io.FileInputStream.open0(Native Method)
12-13 14:00:06.878  6684  6698 E StdOutDevice: 	at java.io.FileInputStream.open(FileInputStream.java:200)
12-13 14:00:06.878  6684  6698 E StdOutDevice: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
....
12-13 14:00:06.878  6684  6698 E StdOutDevice: 	at java.lang.Thread.run(Thread.java:764)
12-13 14:00:06.959  6684  6698 E VysorControl: video error
12-13 14:00:06.959  6684  6698 E VysorControl: java.lang.Exception: Encoder Error
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.vysor.VysorControl.writer(VysorControl.kt:11)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.vysor.VysorDaemon$setupVideoServer$1$1.invokeSuspend(VysorDaemon.kt:15)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at b.t2.n.a.a.resumeWith(ContinuationImpl.kt:3)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at b.t2.k.resumeWith(SafeContinuationJvm.kt:4)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at 
...
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.scratch.event.AsyncEventLoop.run(nioloop.kt:7)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.scratch.event.NioloopKt$startThread$1.run(nioloop.kt:1)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at java.lang.Thread.run(Thread.java:764)
12-13 14:00:06.959  6684  6698 E VysorControl: Caused by: java.lang.AssertionError: java.lang.NoSuchMethodException: createDisplay [class java.lang.String, boolean]
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.virtualdisplay.SurfaceControlVirtualDisplayFactory.createVirtualDisplay(SurfaceControlVirtualDisplayFactory.java:20)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.virtualdisplay.EncoderDevice.registerVirtualDisplay(EncoderDevice.java:5)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.vysor.VysorControl.writer(VysorControl.kt:8)
12-13 14:00:06.959  6684  6698 E VysorControl: 	... 18 more
12-13 14:00:06.959  6684  6698 E VysorControl: Caused by: java.lang.NoSuchMethodException: createDisplay [class java.lang.String, boolean]
12-13 14:00:06.959  6684  6698 E VysorControl: 	at java.lang.Class.getMethod(Class.java:2068)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
12-13 14:00:06.959  6684  6698 E VysorControl: 	at com.koushikdutta.virtualdisplay.SurfaceControlVirtualDisplayFactory.createVirtualDisplay(SurfaceControlVirtualDisplayFactory.java:2)
12-13 14:00:06.959  6684  6698 E VysorControl: 	... 20 more```

**Comment by koush** [comment]
Thanks for the logcat, that’s exactly what I need. Do you know what Android version this is?

**Comment by koush** [comment]
Alternatively, if you are a developer, can you use reflection to enumerate the methods on SurfaceControl?

```java
            final Class surfaceControlClass = Class.forName("android.view.SurfaceControl”);
           Method[] methods = surfaceControlClass.getDeclaredMethods(); // print this out for me
```

**Comment by shervinafshar** [comment]
Thank you for quick response. Android version on the device is 8.0.0. Regarding checking the enum with reflection, although I'm a developer, unfortunately I haven't done any Android development. What's the easiest way to try this code out and get you the results? Empty app on Android Studio? If you do send me a quick app or unit test, I can run it on the device and report the results.

Thanks again.

**Comment by koush** [comment]
Sure, give me a bit and I'll make a dummy app that dumps it to the log.

**Comment by koush** [comment]
Don't have time to do this, so I'm closing. General policy is that non-Google approved devices are unsupported (for this precise reason)

**Comment by shervinafshar** [comment]
Fine. This is a Google headset, FYI.

**Comment by koush** [comment]
Download this and run it and get me the logcat 

https://clockworkmod.s3.amazonaws.com/test/app-release.apk

**Comment by koush** [comment]
The log should look something like this:

```
07-08 17:16:10.041  3226  3226 I System.out: closeTransaction
07-08 17:16:10.042  3226  3226 I System.out: createDisplay
07-08 17:16:10.042  3226  3226 I System.out: class java.lang.String boolean
07-08 17:16:10.043  3226  3226 I System.out: destroyDisplay
07-08 17:16:10.043  3226  3226 I System.out: interface android.os.IBinder
07-08 17:16:10.043   664  3780 D MtkOmxVencV4L2: [0xf4094d00] AVC QTime=8556 us, CvtTime=0 us, FrameCount=529/529/527/527, BsCount=540/540/528/528, ts=47457232 (47457232397), VA=0xF4601D20, len=12, offset=0x00000000, flags=0x00000010 Key(0) Eos(0) Corrupted(0)
07-08 17:16:10.043  3226  3226 I System.out: getDisplayConfigs
07-08 17:16:10.043  3226  3226 I System.out: interface android.os.IBinder
07-08 17:16:10.043  3226  3226 I System.out: openTransaction
07-08 17:16:10.043  3226  3226 I System.out: screenshot
07-08 17:16:10.043  3226  3226 I System.out: class android.graphics.Rect int int int
07-08 17:16:10.043  3226  3226 I System.out: screenshot
07-08 17:16:10.044  3226  3226 I System.out: class android.graphics.Rect int int boolean int
07-08 17:16:10.044  3226  3226 I System.out: setDisplayLayerStack
07-08 17:16:10.044  3226  3226 I System.out: interface android.os.IBinder int
07-08 17:16:10.044  3226  3226 I System.out: setDisplayProjection
07-08 17:16:10.044  3226  3226 I System.out: interface android.os.IBinder int class android.graphics.Rect class android.graphics.Rect
07-08 17:16:10.044  3226  3226 I System.out: setDisplaySurface
07-08 17:16:10.044  3226  3226 I System.out: interface android.os.IBinder class android.view.Surface
07-08 17:16:10.044  3226  3226 I System.out: describeContents
07-08 17:16:10.045  3226  3226 I System.out: finalize
07-08 17:16:10.045  3226  3226 I System.out: hide
07-08 17:16:10.045  3226  3226 I System.out: isValid
07-08 17:16:10.045  3226  3226 I System.out: readFromParcel
07-08 17:16:10.045  3226  3226 I System.out: class android.os.Parcel
07-08 17:16:10.045  3226  3226 I System.out: release
07-08 17:16:10.045  3226  3226 I System.out: setCastMode
07-08 17:16:10.045  3226  3226 I System.out: boolean
07-08 17:16:10.045  3226  3226 I System.out: setFlagsFromSV
07-08 17:16:10.045  3226  3226 I System.out: boolean
07-08 17:16:10.045  3226  3226 I System.out: setLayer
07-08 17:16:10.045  3226  3226 I System.out: int
07-08 17:16:10.045  3226  3226 I System.out: setPosition
07-08 17:16:10.045  3226  3226 I System.out: float float
07-08 17:16:10.045  3226  3226 I System.out: setRecordHide
07-08 17:16:10.045  3226  3226 I System.out: boolean
07-08 17:16:10.045  3226  3226 I System.out: show
07-08 17:16:10.045  3226  3226 I System.out: toString
07-08 17:16:10.045  3226  3226 I System.out: writeToParcel
07-08 17:16:10.045  3226  3226 I System.out: class android.os.Parcel int
07-08 17:16:10.057  3226  3226 V PhoneWindow: DecorView setVisiblity: visibility = 4, Pare
```
